name: CodSpeed

on:
  push:
    branches:
      - main
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # for OpenID Connect authentication with CodSpeed

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Set Up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Benchmarks
        run: pnpm build:node

      - name: Run Benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: node build/benchmarks/search.bench.js
